### ISSUE TITLE
Awesome

### ISSUE THREAD

**Issue by andyscott12** [pcrawfor/FayeObjC#4]
Hey this is pretty awesome

Is this still being maintained or is this no longer relevant ?

**Comment by pcrawfor** [comment]
Hey,

I am around and running this in production on several apps - I actually have a decent 2.0 in the works that makes some improvements and changes out the underlying websocket lib to use socketrocket.  Been using it in a new mac app that is in development.  Just need to find time to pull out and document the changes

**Comment by andyscott12** [comment]
Oh that would be totally awesome if you could do that @pcrawfor - i would be more than happy to help maintain it.

Really looking for something to work with Faye on the iPhone and this is the only lib I found find - so it would be totally awesome if you were willing to release an update to it!

**Comment by andyscott12** [comment]
hey @pcrawfor - thanks so much for the update!

just wondering whether you have any time to provide some new examples and a small update to logic and stuff so I can figure it out ? that would be great. thanks again

**Comment by liquid1982** [comment]
@pcrawfor great job! I hope to see some updates on this project soon, as we decided to use Faye for a web project that has an iPhone client too. Please let us know any news :+1:

**Comment by steveluscher** [comment]
If you have the time, please do check out the [2_0 branch](https://github.com/pcrawfor/FayeObjC/tree/2_0). Give it a shakedown and send us your comments. We're planning on releasing it soon.
